### ISSUE TITLE
Pickle loading error

### ISSUE THREAD

**Issue by tigger-3** [TPrime001/Gerichtsurteile#2]
**. Traceback (most recent call last):
. . File "C:/Users/Sebastian/PycharmProjects/Papenburg/Gerichtsurteile/GUI.py", line 3, in <module>
. . .  from Query import info
. . File "C:\Users\Sebastian\PycharmProjects\Papenburg\Gerichtsurteile\Query.py", line 4, in <module>
. . .  from Query_IBSearch import filteroutput, filtershortcuts, info
. . File "C:\Users\Sebastian\PycharmProjects\Papenburg\Gerichtsurteile\Query_IBSearch.py", line 11, in... 
. . ...<module>
. . .  index = pickle.load(f)
. . _pickle.UnpicklingError**

**Comment by 1-alex98** [comment]
Cool
Ich gucks mir an, wenn ich wieder Internet hab :#

Am 18.08.2016 6:02 AM schrieb "tigger-3" notifications@github.com:

**Comment by 1-alex98** [comment]
ich muss erstmal alles neu installieren dauert was (anderer Computer)
